### ISSUE TITLE
Ability store climb descriptions in database

### ISSUE THREAD

**Issue by lgrosz** [lgrosz/climb-rs#22]
Climbs are often described with more than just their name. More often than not, this would simply manifest in a single "description." However, in my own experience and note-taking endeavors I often would have a much larger description followed by minimizing it in to a "brief." There are also other descriptions which could be made such as historical ones.

Because of this, a dynamic way of storing many descriptions per climb seems warranted. A table like...

```
climb_descriptions:
  header: String
    - pk
  climb_id: Int
    - references climbs::id
    - pk
  content: String
```

... may work.
